## numpy array

In [1]:
import numpy as np

In [2]:
l = [0, 1, 2, 3]
l

[0, 1, 2, 3]

In [5]:
l = list(range(4))
l

[0, 1, 2, 3]

In [6]:
np.array(l)

array([0, 1, 2, 3])

In [7]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [9]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.arange(0, 4, 1)

array([0, 1, 2, 3])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0, 10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(1)

array([0.43441255])

In [30]:
np.random.rand(5)

array([0.42784266, 0.14455591, 0.81022197, 0.97411524, 0.4225482 ])

In [31]:
np.random.rand(2, 3)

array([[0.22858908, 0.59246832, 0.49252933],
       [0.27025037, 0.80218608, 0.92684055]])

In [42]:
np.random.randint(1, 10, 2)

array([1, 6])

In [44]:
my_arr = np.random.rand(5)
my_arr

array([0.14048754, 0.8470696 , 0.94776333, 0.75329009, 0.84245881])

In [45]:
my_arr.max()

0.947763330992846

In [46]:
my_arr.argmax()

2

In [47]:
my_arr.min()

0.14048754016230258

In [48]:
my_arr.argmin()

0

In [49]:
my_arr = np.array([[1, 2, 3], [4, 5, 6]])
my_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
my_arr.shape

(2, 3)

In [52]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
my_arr.shape

(10,)

In [56]:
new_arr = my_arr.reshape(2, 5)
new_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
new_arr = my_arr.reshape(5, 2)
new_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
new_arr = my_arr.reshape(10, 1)
new_arr

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [59]:
new_arr = my_arr.reshape(1, 10)
new_arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
print(my_arr.shape)
print(new_arr.shape)

(10,)
(1, 10)
