## numpy operations

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr / arr

C:\Users\Reza\AppData\Local\Temp/ipykernel_13168/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [9]:
arr * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
1 / arr

C:\Users\Reza\AppData\Local\Temp/ipykernel_13168/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
np.sqrt(arr ** 2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
np.log(arr)

C:\Users\Reza\AppData\Local\Temp/ipykernel_13168/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
arr.max()

9

In [20]:
np.max(arr)

9

In [21]:
np.argmax(arr)

9

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.argmin(arr)

0

In [24]:
np.min(arr)

0

In [25]:
new_arr = np.arange(4)
new_arr

array([0, 1, 2, 3])

In [26]:
new_arr.sum()

6

In [27]:
new_arr.mean()

1.5

In [28]:
np.sum(new_arr)

6

In [29]:
print(np.ones(10))
np.std(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


0.0

In [30]:
new_arr

array([0, 1, 2, 3])

In [31]:
new_arr.shape

(4,)

In [32]:
new_arr.shape[0]

4