## numpy indexing

In [33]:
import numpy as np

In [34]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[0]

0

In [36]:
arr[-1]

10

In [37]:
arr[:4]

array([0, 1, 2, 3])

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# arr[row, col]
arr[0, 0]

1

In [40]:
arr[-1, -1]

6

In [41]:
arr[0, 2]

3

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr[:, 1:]

array([[2, 3],
       [5, 6]])

In [44]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_1 = arr[:4]
slice_1

array([0, 1, 2, 3])

In [47]:
slice_1[:] = 100
print(slice_1)
arr

[100 100 100 100]


array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [48]:
slice_1 = arr[:4].copy()
slice_1

array([100, 100, 100, 100])

In [49]:
slice_1[:] = 200
print(slice_1)
arr

[200 200 200 200]


array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [51]:
print(arr)
arr[0:4] = 20
arr

[100 100 100 100   4   5   6   7   8   9  10]


array([20, 20, 20, 20,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr[0]

array([1, 2, 3])

In [55]:
arr[:, 0]

array([1, 4])

In [56]:
new_arr = np.arange(11)
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
new_arr >= 8

array([False, False, False, False, False, False, False, False,  True,
        True,  True])

In [58]:
new_arr < 2

array([ True,  True, False, False, False, False, False, False, False,
       False, False])

In [59]:
new_arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [60]:
b = new_arr >= 8
print(new_arr)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False False False  True  True  True]


In [61]:
new_arr[b]

array([ 8,  9, 10])

In [62]:
new_arr[new_arr >= 8]

array([ 8,  9, 10])

In [63]:
new_arr[new_arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [64]:
b = new_arr >= 8
print(new_arr)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False False False  True  True  True]


In [66]:
b.all()

False

In [67]:
b.any()

True

In [69]:
np.array([True, True, True, True]).all()

True