## Numpy_exercise

##### یک آرایه نامپای یک بعدی شامل ده تا عدد ده بسازید 

##### یک آرایه نامپای از اعداد زوج ده تا پنجاه بسازید

##### یک آرایه نامپای  سه در سه از اعداد 0 تا 8 بسازید
##### [[0 1 2] [3 4 5] [6 7 8]]

##### با استفاده از نامپای یک عدد تصادفی از صفر تا یک بسازید

###  -------------------------------------------------------------------------------------------------------------------

##### آرایه زیر را در نظر بگیرید

In [1]:
import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#####  آرایه پایین را به صورت قسمتی از آرایه بالا بدست آورید

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

##### عدد 19 را از دل آرایه بیرون بکشید

##### ردیف آخر آرایه را بدست آورید

##### دو ردیف آخر آرایه را بدست آورید

##### مجموع تمام اعضای آرایه را بدست آورید یعنی عدد 325

In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### مجموع هر کدام از پنج ردیف را بدست آورید
##### Use the (axis) argument :           axis=0         &            axis=1 

##### مجموع هر کدام از پنج ستون را بدست آورید

##### تمام اعضای ماتریس را که بر سه بخشپذیرند نمایش دهید

array([ 3,  6,  9, 12, 15, 18, 21, 24])

##### تمامی حقوق برای رضا علوی محفوظ است