## Numpy_exercise

##### یک آرایه نامپای یک بعدی شامل ده تا عدد ده بسازید 

In [2]:
import numpy as np
np.ones(10) * 10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [3]:
np.zeros(10) + 10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

##### یک آرایه نامپای از اعداد زوج ده تا پنجاه بسازید

In [5]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##### یک آرایه نامپای  سه در سه از اعداد 0 تا 8 بسازید
##### [[0 1 2] [3 4 5] [6 7 8]]

In [8]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### با استفاده از نامپای یک عدد تصادفی از صفر تا یک بسازید

In [19]:
np.random.rand(1)[0]
# numpy random seed

0.1696539711222883

###  -------------------------------------------------------------------------------------------------------------------

##### آرایه زیر را در نظر بگیرید

In [1]:
import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#####  آرایه پایین را به صورت قسمتی از آرایه بالا بدست آورید

In [23]:
arr = np.arange(1, 26).reshape(5, 5)
arr[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

##### عدد 19 را از دل آرایه بیرون بکشید

In [25]:
arr[3, 3]

19

##### ردیف آخر آرایه را بدست آورید

In [26]:
arr[-1, :]

array([21, 22, 23, 24, 25])

##### دو ردیف آخر آرایه را بدست آورید

In [29]:
print(arr)
arr[-2:, :]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### مجموع تمام اعضای آرایه را بدست آورید یعنی عدد 325

In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr.sum()

325

##### مجموع هر کدام از پنج ردیف را بدست آورید
##### Use the (axis) argument :           axis=0         &            axis=1 

In [33]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])

##### مجموع هر کدام از پنج ستون را بدست آورید

In [34]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

##### تمام اعضای ماتریس را که بر سه بخشپذیرند نمایش دهید

In [35]:
arr[arr%3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24])

array([ 3,  6,  9, 12, 15, 18, 21, 24])

##### تمامی حقوق برای رضا علوی محفوظ است

In [1]:
import numpy as np
a = np.array([0,1,2,3,4,5,6])

In [2]:
def f(arr, i):
    return arr[:i]

In [ ]:
f(a,0)