## Relative extrema

In [1]:
import numpy as np

In [2]:
x = np.array([2, 1, 2, 3, 2, 0, 1, 1, 3, 4, 2, 0, 1, 2])
x

array([2, 1, 2, 3, 2, 0, 1, 1, 3, 4, 2, 0, 1, 2])

In [3]:
# Calculate the relative extrema of data
# Peak : Relative maximum  
# Trough : Relative minimum

# argrelextrema( data = x, comparator = np.greater, order = 1)

# np.greater, np.greater_equal, np.less, np.less_equal

In [4]:
from scipy.signal import argrelextrema

In [7]:
# peaks
peaks_ind = argrelextrema(data=x, comparator=np.greater, order=1)[0]
peaks_ind

array([3, 9], dtype=int64)

In [8]:
# troughs
troughs_ind = argrelextrema(data=x, comparator=np.less, order=1)[0]
troughs_ind

array([ 1,  5, 11], dtype=int64)

In [9]:
x

array([2, 1, 2, 3, 2, 0, 1, 1, 3, 4, 2, 0, 1, 2])

In [10]:
peaks = np.zeros(x.shape)
troughs = np.zeros(x.shape)
print(peaks, troughs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
peaks[peaks_ind] = True
troughs[troughs_ind] = True
print(peaks, troughs)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]


In [12]:
for i in range(len(x)):
    print('for x = ', x[i], ', is peak =', peaks[i], ', is trough =', troughs[i])

for x =  2 , is peak = 0.0 , is trough = 0.0
for x =  1 , is peak = 0.0 , is trough = 1.0
for x =  2 , is peak = 0.0 , is trough = 0.0
for x =  3 , is peak = 1.0 , is trough = 0.0
for x =  2 , is peak = 0.0 , is trough = 0.0
for x =  0 , is peak = 0.0 , is trough = 1.0
for x =  1 , is peak = 0.0 , is trough = 0.0
for x =  1 , is peak = 0.0 , is trough = 0.0
for x =  3 , is peak = 0.0 , is trough = 0.0
for x =  4 , is peak = 1.0 , is trough = 0.0
for x =  2 , is peak = 0.0 , is trough = 0.0
for x =  0 , is peak = 0.0 , is trough = 1.0
for x =  1 , is peak = 0.0 , is trough = 0.0
for x =  2 , is peak = 0.0 , is trough = 0.0


##### تمامی حقوق برای رضا علوی محفوظ است